//! `servicrab init` — generate an example `servicrab.toml`.

use std::path::Path;

use anyhow::{bail, Context};

/// Template written by `servicrab init`.
const EXAMPLE_TOML: &str = r#"# servicrab.toml — generated by `servicrab init`
#
# Edit this file to describe the processes that make up your local stack.
# Run `servicrab check` to validate it, `servicrab list` to see the services,
# and `servicrab run <name>` to start a service in the foreground.

[project]
name = "my-project"

# ── Services ──────────────────────────────────────────────────────────────────
# Each [services.<name>] block defines one managed process.
# Fields:
#   command     (required) Shell command used to start the service.
#   cwd         (optional) Working directory; defaults to the config file's dir.
#   restart     (optional) never | on-failure | always  (default: never)
#   depends_on  (optional) List of service names that must run first.
#   env         (optional) Extra environment variables.

[services.api]
command = "echo 'Replace me with your API server command'"
cwd = "."
restart = "on-failure"
depends_on = ["db"]

[services.db]
command = "echo 'Replace me with your database command'"
restart = "always"

[services.worker]
command = "echo 'Replace me with your worker command'"
restart = "never"

[services.worker.env]
DATABASE_URL = "postgres://localhost/mydb"
"#;

/// Run the `init` subcommand.
pub fn run() -> anyhow::Result<()> {
    let path = Path::new("servicrab.toml");

    if path.exists() {
        bail!(
            "{} already exists. Remove it first or edit it manually.",
            path.display()
        );
    }

    std::fs::write(path, EXAMPLE_TOML)
        .with_context(|| format!("could not write {}", path.display()))?;

    println!(
        "Created {}. Edit it, then run `servicrab check`.",
        path.display()
    );
    Ok(())
}
