//! `servicrab init [--path PATH] [--force]` — create an example config file.

use std::path::Path;

/// Template written by `servicrab init`.
const EXAMPLE_TOML: &str = r#"# servicrab.toml — generated by `servicrab init`
#
# Edit this file to describe the processes that make up your local stack.
# Run `servicrab check` to validate it and `servicrab list` to see the
# services.

version = 1

[project]
name = "my-project"

# ── Project-level environment variables ───────────────────────────────────────
# These are merged into every service's environment (service env takes
# precedence over project env, which takes precedence over the inherited shell
# environment).
# [project.env]
# RUST_LOG = "info"

# ── Environment files ─────────────────────────────────────────────────────────
# Dotenv-style files loaded for every service.  Paths are relative to this file.
# Layering, later wins:  shell env -> project env_file -> [project.env]
#                        -> service env_file -> [services.<name>.env]
# env_file = ".env"
# env_file = [".env", ".env.local"]

# ── Log files ─────────────────────────────────────────────────────────────────
# Uncomment to keep a copy of every service's output on disk.  Files are
# rotated once they cross max_size:  api.log -> api.log.1 -> api.log.2 ...
# Read them back with `servicrab logs [SERVICE] [-f] [-n N]`.
# [project.logs]
# dir = ".servicrab/logs"   # relative to this file (default)
# max_size = "10MB"         # rotate above this size (default)
# max_files = 3             # rotated generations to keep (default)

# ── Services ──────────────────────────────────────────────────────────────────
# Each [services.<name>] block defines one managed process.
#
# Required fields:
#   command       List of executable + arguments, e.g. ["node", "server.js"]
#
# Optional fields:
#   cwd           Working directory (default: config file's directory)
#   env           Per-service environment variables
#   env_file      Dotenv file(s) loaded before `env`, e.g. ".env" or a list
#   depends_on    Services that must start before this one, e.g. ["db"]
#   autostart     Whether to start automatically (default: true)
#   restart       never | on-failure | always  (default: never)
#   restart_delay         Minimum backoff before first restart (default: 1s)
#   restart_max_delay     Maximum backoff cap (default: 30s)
#   max_restarts          Give up after this many attempts (default: 10)
#   stable_after          Consider stable after running this long (default: 60s)
#   shutdown_signal       term | int | quit | hup  (default: term)
#   shutdown_timeout      Wait this long before forcibly killing (default: 10s)
#
# Optional [services.<name>.watch] block — restart on file changes:
#   paths         Files/directories to watch, relative to the service's cwd
#   ignore        Names, "dir/prefix" or "*.ext" entries never to watch
#                 (.git and .servicrab are always ignored)
#   interval      How often the tree is scanned (default: 1s)
#   debounce      Quiet period before the restart fires (default: 300ms)
#
# Optional [services.<name>.logs] block:
#   enabled       Write this service's output to a log file (default: true,
#                 only has an effect when [project.logs] exists)
#
# Optional [services.<name>.health] block — exactly one probe:
#   command       Probe command; exit code 0 means healthy
#   http          Plain-HTTP URL that must answer 2xx/3xx, e.g. "http://127.0.0.1:3000/health"
#   tcp           "host:port" that must accept a connection
#   interval      Delay between probes (default: 2s)
#   timeout       Per-probe timeout (default: 5s)
#   retries       Consecutive failures before unhealthy (default: 3)
#   start_period  Grace period after start (default: 0s)
#   on_unhealthy  restart | ignore (default: restart)
#
# Services that depend on a health-checked service wait for its first
# successful probe instead of just for its process to be up.

[services.api]
command = ["echo", "Replace me with your API server command"]
cwd = "."
restart = "on-failure"
restart_delay = "1s"
restart_max_delay = "30s"
max_restarts = 5
depends_on = ["db"]

[services.api.env]
PORT = "3000"

[services.db]
command = ["echo", "Replace me with your database command"]
restart = "always"

# [services.db.health]
# tcp = "127.0.0.1:5432"
# interval = "2s"
# start_period = "5s"

[services.worker]
command = ["echo", "Replace me with your worker command"]
restart = "never"
autostart = false

[services.worker.env]
DATABASE_URL = "postgres://localhost/mydb"

# [services.worker.watch]
# paths = ["src", "package.json"]
# ignore = ["target", "node_modules", "*.log"]
"#;

/// Run the `init` subcommand.
pub fn run(path: &Path, force: bool) -> Result<(), String> {
    if path.exists() && !force {
        return Err(format!(
            "{} already exists. Use --force to overwrite, or edit it manually.",
            path.display()
        ));
    }

    std::fs::write(path, EXAMPLE_TOML)
        .map_err(|e| format!("could not write {}: {e}", path.display()))?;

    println!(
        "Created {}. Edit it, then run `servicrab check`.",
        path.display()
    );
    Ok(())
}
